import type { Metadata } from "next";
import type { PropsWithChildren, ReactElement } from "react";
import { Inter } from "next/font/google";
import { Providers } from "#/lib/providers/tanstack-query";
import "#/lib/styles/tailwind.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function Layout({ children }: PropsWithChildren): ReactElement {
  return (
    <html>
      <body className={`text-white bg-black flex items-center justify-center h-screen ${inter.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}